on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    # - name: Install PNPM
    #   uses: pnpm/action-setup@v2
    #   with:
    #     version: 8 

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        # cache: pnpm

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright browsers
      run: pnpm playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Build static content
      run: CI= pnpm run build

    - name: Change directory to dist
      run: cd dist
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.ftp_server }}
        username: ${{ vars.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
        server-dir: ./public_html/
